/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ThermalCraftDialog.java
 *
 * Created on Mar 10, 2011, 8:41:11 PM
 */
package thermalcraft;

/**
 *
 * @author Marc Schweikert
 */
public class ThermalCraftDialog extends javax.swing.JDialog {

	/** Creates new form ThermalCraftDialog */
	public ThermalCraftDialog(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		getRootPane().setDefaultButton(closeButton);
	}

	public void setLabelText(String text) {
		dialogLabel.setText(text);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogLabel = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(thermalcraft.ThermalCraftApp.class).getContext().getResourceMap(ThermalCraftDialog.class);
        setTitle(resourceMap.getString("errorDialog.title")); // NOI18N
        setAlwaysOnTop(true);
        setName("errorDialog"); // NOI18N

        dialogLabel.setFont(resourceMap.getFont("dialogLabel.font")); // NOI18N
        dialogLabel.setText(resourceMap.getString("dialogLabel.text")); // NOI18N
        dialogLabel.setName("dialogLabel"); // NOI18N

        closeButton.setText(resourceMap.getString("closeButton.text")); // NOI18N
        closeButton.setName("closeButton"); // NOI18N
        closeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dialogLabel)
                .addContainerGap(362, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(331, Short.MAX_VALUE)
                .addComponent(closeButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dialogLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(closeButton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void closeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonMouseClicked
		dispose();
	}//GEN-LAST:event_closeButtonMouseClicked

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {

			public void run() {
				ThermalCraftDialog dialog = new ThermalCraftDialog(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {

					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel dialogLabel;
    // End of variables declaration//GEN-END:variables
}
